### ISSUE TITLE
Force linting of staged files

### ISSUE THREAD

**Issue by bostrom** [motleyagency/eslint-config-motley#51]
Lint errors go unnoticed unless the developer has a linter enabled in the editor, an even then the developer can choose to ignore lint errors. Perhaps we could force linting of staged files?

``` diff
  "lint-staged": {
    "*.{js,json,graphql,md,css,scss,less,ts}": [
+     "eslint --fix",
      "prettier --write",
      "git add"
    ]
  }
```

**Comment by petetnt** [comment]
That's fine with me, caveat is that `eslint` is really bad at `--fix`:ing things not related styles and those Prettier does much better job at. 🤷‍♂️ Not sure what the specific order should be either? For example `eslint-disable-next-line` easily breaks when `prettier` applies now lines 🤔

**Comment by bostrom** [comment]
Hm yes. And actually the above config won't work since it tries to run eslint on .json files for example and that will always break. So perhaps a solution is to just override the lint-staged config with your own, which could include the eslint command if desired. 

#50 enables this by not overwriting the lint-staged config each time the package is installed.
