### ISSUE TITLE
Doesn't work well with staged hunks

### ISSUE THREAD

**Issue by bostrom** [motleyagency/eslint-config-motley#57]
Staging just hunks of files using interactive add still commits the whole file since the whole file is re-added after processing.

**Comment by petetnt** [comment]
This has been fixed in https://github.com/okonet/lint-staged/releases/tag/v8.0.0, PRz plz

**Comment by bostrom** [comment]
Nice! Will make PR.

**Comment by bostrom** [comment]
Closed by #58
