### ISSUE TITLE
Update eslint-plugin-react-hooks to ^1.6.0

### ISSUE THREAD

**Issue by petetnt** [motleyagency/eslint-config-motley#62]

**Comment by valstu** [comment]
This is now included in the create-react-app also, so should we remove it from here completely since probably 99% of our react projects are based on CRA? Also CRA uses rule
`'react-hooks/exhaustive-deps': 'warn'` and we have 
`'react-hooks/exhaustive-deps': 'error'`

**Comment by petetnt** [comment]
Was updated in #64
