### ISSUE TITLE
Missing file extension errors

### ISSUE THREAD

**Issue by valstu** [motleyagency/eslint-config-motley#65]
![image](https://user-images.githubusercontent.com/647861/72805274-28a7d680-3c5b-11ea-93e4-b246acab270c.png)

So I'm getting these missing file extension errors for `.ts` and `.tsx` files for some reason. Apparently having the same issue as this user: https://stackoverflow.com/questions/59265981/typescript-eslint-missing-file-extension-ts-import-extensions

**Comment by petetnt** [comment]
Fixed in #66
