### ISSUE TITLE
ESLint couldn't find the config "motley" to extend from.

### ISSUE THREAD

**Issue by petetnt** [motleyagency/eslint-config-motley#71]
This now happens with v13 at least:

Oops! Something went wrong! :(

ESLint: 7.11.0

ESLint couldn't find the config "motley" to extend from. Please check that the name of the config is correct.

The config "motley" was referenced from the config file in "/Users/Nykanen/Projects/other/.eslintrc.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

**Comment by petetnt** [comment]
This is probably due to conflicting `.eslintrc.js` existing in the same project tree, @bostrom needs to follow up

**Comment by bostrom** [comment]
Yes, problem solved by removing an `.eslintrc.js` found in an ancestor directory of the project root dir.
