### ISSUE TITLE
Upgrade TS to 4.x

### ISSUE THREAD

**Issue by sirtawast** [motleyagency/eslint-config-motley#79]
Hi, just tried out Vite 2 and it's not compatible with TS3 anymore. The Typescript side would need a version bump. This would not break any other setup as this is config is a one-off.

**Comment by petetnt** [comment]
What was the error you received?

**Comment by petetnt** [comment]
The error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../dist/node/cli'
Require stack:
- /Users/Nykanen/Projects/motley/motley-x/node_modules/.bin/vite
```

**Comment by petetnt** [comment]
Just confirmed, the parsers need updates too
